# Copyright © Niantic Spatial, Inc. 2025. All rights reserved.
"""Module to create training buffer given a dataset and encoder."""

import logging
import os
import random
from typing import Optional

import dataclasses
import numpy as np
import torch
import torchvision.transforms.functional as TF
import tqdm
from torch.utils.data import DataLoader, sampler

from ace_g import datasets, encoders, utils

_logger = logging.getLogger(__name__)


def worker_init_fn(worker_id: int) -> None:
    """Worker initialization function.

    Sets the seed, the CPU affinity, and the multiprocessing sharing strategy.
    """
    # Different seed per epoch. Initial seed is generated by the main process consuming one random number from
    # the dataloader generator, so this will increment by 1 for each worker.
    # Also torch's seed is automatically set to base_seed + worker_id for each worker, so no there's no need to set it
    # here. See: https://docs.pytorch.org/docs/stable/data.html#randomness-in-multi-process-data-loading
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)

    # Set the affinity of the worker to all available cores.
    # This is a workaround for an issue with PyTorch's conda package, but shouldn't cause problems otherwise.
    # See: https://github.com/pytorch/pytorch/issues/99625
    num_cores = os.cpu_count()
    if num_cores is not None:
        os.sched_setaffinity(0, range(num_cores))

    # Set multiprocess sharing strategy to file_system to avoid too many open files error.
    torch.multiprocessing.set_sharing_strategy("file_system")


@dataclasses.dataclass
class PatchBuffer:
    """Collection of tensors required for patch-based scene coordinate training."""

    features: torch.Tensor
    """Batch of features sampled from images. Shape (B*num_samples_per_image, encoder.dim_out)."""
    target_px: torch.Tensor
    """Pixel coordinate of original image corresponding to the center of the patch used to compute the feature.
    Shape (B*num_samples_per_image, 2)."""
    aug_poses_inv: torch.Tensor
    """Original camera to augmented camera transform. Shape (B*num_samples_per_image, 3, 4)."""
    poses_inv: torch.Tensor
    """World to original camera transform. Shape (B*num_samples_per_image, 4, 4)."""
    intrinsics: torch.Tensor
    """Camera intrinsics (i.e., image-from-camera transform). Shape (B*num_samples_per_image, 3, 3)."""
    intrinsics_inv: torch.Tensor
    """Inverse of the camera intrinsics (i.e., camera-from-image transform). Shape (B*num_samples_per_image, 3, 3)."""
    target_crds: torch.Tensor
    """3D world coordinates for each feature. Shape (B*num_samples_per_image, 3)."""
    pose_idx: torch.Tensor
    """Index of the pose / image / etc. (i.e., index passed to the dataset to retrieve the image).
    Shape (B*num_samples_per_image, 1)."""
    resolution: torch.Tensor
    """Resolution of the images. Shape (B, 2)."""


def create_buffer(
    dataset: datasets.CamLocDataset,
    encoder: encoders.Encoder,
    max_buffer_size: int,
    buffer_device: str,
    max_dataset_passes: int,
    num_data_loader_workers: int | None,
    num_samples_per_image: int,
    use_half: bool,
    seed: int,
    pin_memory: bool = True,
    persistent_workers: bool = True,
    batch_size: int = 1,
) -> PatchBuffer:
    """Create training buffer given a dataset and encoder.

    Args:
        dataset: Dataset to sample from.
        encoder: Encoder used to compute features.
        max_buffer_size: Maximum size of the buffer.
        buffer_device: Device where the buffer will be stored. Computation happens on the device of the encoder.
        max_dataset_passes: Maximum number of passes over the dataset.
        num_data_loader_workers: Number of workers for the DataLoader. If None, number of CPU cores is used.
        num_samples_per_image:
            Number of patches sampled per image. Not used if keep_image_dim is True.
        seed: Seed for the random number generators.
        pin_memory: Whether to use pinned memory for the DataLoader.
        persistent_workers: Whether to keep the workers alive between epochs.
        batch_size: Batch size used in the DataLoader.
    """
    dataset.set_subsample_factor(encoder.subsample_factor)

    device = next(encoder.parameters()).device
    batch_generator = torch.Generator()
    batch_generator.manual_seed(seed + 1023)
    loader_generator = torch.Generator()
    loader_generator.manual_seed(seed + 511)
    sampling_generator = torch.Generator(device=device)
    sampling_generator.manual_seed(seed + 4095)

    pixel_grid_2hw = utils.get_pixel_grid(encoder.subsample_factor)
    pixel_grid_2hw = pixel_grid_2hw.to(device)

    # Disable benchmarking, since we have variable tensor sizes.
    torch.backends.cudnn.benchmark = False

    assert len(dataset) > 0, "Dataset must contain at least one image."

    # Sampler.
    batch_sampler = sampler.BatchSampler(
        sampler.RandomSampler(dataset, generator=batch_generator),
        batch_size=batch_size,  # higher should be better for GPU utilization as long as workers can keep up
        drop_last=False,
    )

    # Batching is handled at the dataset level (the dataset __getitem__ receives a list of indices, because we
    # need to rescale all images in the batch to the same size).
    if num_data_loader_workers is None:
        num_data_loader_workers = os.cpu_count()
        assert num_data_loader_workers is not None, "Number of CPU cores could not be determined."
    training_dataloader = DataLoader(
        dataset=dataset,
        sampler=batch_sampler,
        batch_size=None,
        worker_init_fn=worker_init_fn,
        generator=loader_generator,
        pin_memory=pin_memory,
        num_workers=num_data_loader_workers,
        persistent_workers=num_data_loader_workers > 0 and persistent_workers,
        timeout=60 if num_data_loader_workers > 0 else 0,
    )

    _logger.info("Starting creation of the training buffer.")

    features_dtype = torch.float16 if use_half else torch.float32

    # Create a training buffer that lives either on the GPU or in main memory.
    patch_buffer: Optional[PatchBuffer] = None

    # Calculate size of the dataset buffer
    buffer_size = max_dataset_passes * len(dataset) * num_samples_per_image
    buffer_size = min(buffer_size, max_buffer_size)
    patch_buffer = PatchBuffer(
        features=torch.empty(
            (buffer_size, encoder.dim_out),
            dtype=features_dtype,
            device=buffer_device,
        ),
        target_px=torch.empty((buffer_size, 2), dtype=torch.float32, device=buffer_device),
        aug_poses_inv=torch.empty((buffer_size, 3, 4), dtype=torch.float32, device=buffer_device),
        poses_inv=torch.empty((buffer_size, 4, 4), dtype=torch.float32, device=buffer_device),
        intrinsics=torch.empty((buffer_size, 3, 3), dtype=torch.float32, device=buffer_device),
        intrinsics_inv=torch.empty((buffer_size, 3, 3), dtype=torch.float32, device=buffer_device),
        target_crds=torch.empty((buffer_size, 3), dtype=torch.float32, device=buffer_device),
        pose_idx=torch.empty((buffer_size, 1), dtype=torch.long, device=buffer_device),
        resolution=torch.empty((buffer_size, 2), dtype=torch.long, device=buffer_device),
    )

    # Features are computed in evaluation mode.
    encoder.eval()

    # The encoder is pretrained, so we don't compute any gradient.
    with torch.no_grad(), tqdm.tqdm(total=buffer_size, desc="Creating training buffer", dynamic_ncols=True) as pbar:
        # Iterate until the training buffer is full.
        buffer_idx = 0
        dataset_passes = 0

        while buffer_idx < max_buffer_size and dataset_passes < max_dataset_passes:
            dataset_passes += 1
            for (
                image_B1HW,
                image_mask_b1hw,
                pose_inv_b44,
                aug_pose_inv_b44,
                intrinsics_b33,
                intrinsics_inv_b33,
                target_crds_b3hw,
                _,
                idx_B,
            ) in training_dataloader:
                # Copy to device.
                image_B1HW = image_B1HW.to(device, non_blocking=True)
                image_mask_b1hw = image_mask_b1hw.to(device, non_blocking=True)
                aug_pose_inv_b44 = aug_pose_inv_b44.to(device, non_blocking=True)
                pose_inv_b44 = pose_inv_b44.to(device, non_blocking=True)
                intrinsics_b33 = intrinsics_b33.to(device, non_blocking=True)
                intrinsics_inv_b33 = intrinsics_inv_b33.to(device, non_blocking=True)
                target_crds_b3hw = target_crds_b3hw.to(device, non_blocking=True)
                idx_B = idx_B.to(device, non_blocking=True)

                # Compute image features.
                with torch.autocast("cuda", enabled=use_half):
                    features_bchw = encoder(image_B1HW)

                features_bchw = features_bchw.to(features_dtype)

                # Dimensions after the network's downsampling.
                B, _, H, W = features_bchw.shape

                if H != target_crds_b3hw.shape[2] or W != target_crds_b3hw.shape[3]:
                    # The dataset has no knowledge whether the encoder skips complete patches and assumes they are not.
                    # This can lead to incorrect spatial dimensions for the target coordinates depending on the encoder.
                    # As a workaround we cut off the target coordinates such that they match the encoder's output.
                    target_crds_b3hw = target_crds_b3hw[:, :, :H, :W]

                # Make sure spatial dimensions match, otherwise something is wrong
                assert features_bchw.shape[2:] == target_crds_b3hw.shape[2:], (
                    f"Spatial dimensions of target coordinates ({features_bchw.shape[2:]=}) coming from dataset must "
                    f"match those of encoder features ({target_crds_b3hw.shape[2:]=})."
                )

                # The image_mask needs to be downsampled to the actual output resolution and cast to bool.
                # FIXME this is not taking into account the encoder's downsampling logic.
                #  Should subsample + crop instead
                image_mask_b1hw = TF.resize(
                    image_mask_b1hw,
                    [H, W],
                    interpolation=TF.InterpolationMode.NEAREST,
                )
                image_mask_b1hw = image_mask_b1hw.bool()

                # If the current mask has no valid pixels, continue.
                if image_mask_b1hw.sum() == 0:
                    continue

                # Create a tensor with the pixel coordinates of every feature vector.
                pixel_positions_b2hw = pixel_grid_2hw[:, :H, :W].clone()  # It's 2xHxW (actual H and W) now.
                pixel_positions_b2hw = pixel_positions_b2hw[None]  # 1x2xHxW
                pixel_positions_b2hw = pixel_positions_b2hw.expand(B, 2, H, W)  # Bx2xHxW

                # Bx4x4 -> Nx3x4 (for each image, repeat pose per feature)
                aug_pose_inv = aug_pose_inv_b44[:, :3]
                aug_pose_inv = aug_pose_inv.unsqueeze(1).expand(B, H * W, 3, 4).reshape(-1, 3, 4)

                # Bx4x4 -> Nx4x4 (for each image, repeat pose per feature)
                pose_inv = pose_inv_b44.unsqueeze(1).expand(B, H * W, 4, 4).reshape(-1, 4, 4)

                # B -> N (for each image, repeat pose index)
                idx_N = idx_B.unsqueeze(-1).expand(B, H * W).reshape(-1, 1)

                # Bx3x3 -> Nx3x3 (for each image, repeat intrinsics per feature)
                intrinsics = intrinsics_b33.unsqueeze(1).expand(B, H * W, 3, 3).reshape(-1, 3, 3)
                intrinsics_inv = intrinsics_inv_b33.unsqueeze(1).expand(B, H * W, 3, 3).reshape(-1, 3, 3)

                def normalize_shape(tensor_in: torch.Tensor) -> torch.Tensor:
                    """Bring tensor from shape BxCxHxW to NxC."""
                    return tensor_in.transpose(0, 1).flatten(1).transpose(0, 1)

                features_NC = normalize_shape(features_bchw)
                pixel_positions_N2 = normalize_shape(pixel_positions_b2hw)
                target_crds_N3 = normalize_shape(target_crds_b3hw)

                # make sure features and targets have matching number of patches
                assert features_NC.shape[0] == pixel_positions_N2.shape[0] == target_crds_N3.shape[0]

                # all images in a batch have same resolution
                resolution_N2 = torch.tensor([H, W], device=device).expand(B * H * W, 2)

                # Turn image mask into sampling weights (all equal).
                image_mask_b1hw = image_mask_b1hw.float()
                image_mask_N1 = normalize_shape(image_mask_b1hw)

                # Over-sample according to image mask.
                features_to_select = num_samples_per_image * B
                features_to_select = min(features_to_select, buffer_size - buffer_idx)

                # Sample indices uniformly, with replacement.
                sample_idxs = torch.multinomial(
                    image_mask_N1.view(-1),
                    features_to_select,
                    replacement=True,
                    generator=sampling_generator,
                )

                # Write to training buffer. Start at buffer_idx and end at buffer_offset - 1.
                buffer_offset = buffer_idx + features_to_select

                # Copy to buffer, if the buffer lives on the GPU the .to() is a noop.
                patch_buffer.features[buffer_idx:buffer_offset] = features_NC[sample_idxs].to(buffer_device)
                patch_buffer.target_px[buffer_idx:buffer_offset] = pixel_positions_N2[sample_idxs].to(buffer_device)
                patch_buffer.aug_poses_inv[buffer_idx:buffer_offset] = aug_pose_inv[sample_idxs].to(buffer_device)
                patch_buffer.poses_inv[buffer_idx:buffer_offset] = pose_inv[sample_idxs].to(buffer_device)
                patch_buffer.intrinsics[buffer_idx:buffer_offset] = intrinsics[sample_idxs].to(buffer_device)
                patch_buffer.intrinsics_inv[buffer_idx:buffer_offset] = intrinsics_inv[sample_idxs].to(buffer_device)
                patch_buffer.target_crds[buffer_idx:buffer_offset] = target_crds_N3[sample_idxs].to(buffer_device)
                patch_buffer.pose_idx[buffer_idx:buffer_offset] = idx_N[sample_idxs].to(buffer_device)
                patch_buffer.resolution[buffer_idx:buffer_offset] = resolution_N2[sample_idxs].to(buffer_device)

                buffer_idx = buffer_offset
                pbar.update(buffer_idx - pbar.n)
                if buffer_idx >= max_buffer_size:
                    break

    # clipping training buffer to actual size
    buffer_size = min(buffer_idx, max_buffer_size)

    # Clip the patch buffer to the requested size.
    if patch_buffer is not None:
        for field in dataclasses.fields(patch_buffer):
            setattr(patch_buffer, field.name, getattr(patch_buffer, field.name)[:buffer_size])

        buffer_memory = sum([v.element_size() * v.nelement() for v in dataclasses.asdict(patch_buffer).values()])
        buffer_memory /= 1024 * 1024 * 1024  # convert to GB

        _logger.info(f"Created buffer of {buffer_memory:.2f}GB with {dataset_passes} passes over the training data.")

    encoder.train()

    return patch_buffer
